/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPagesRouteImport } from './routes/_authenticated/pages'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMConversationIdRouteImport } from './routes/_authenticated/m.$conversationId'
import { Route as AuthenticatedPPostIdRouteImport } from './routes/_authenticated/p.$postId'
import { Route as AuthenticatedPgSlugRouteImport } from './routes/_authenticated/pg.$slug'
import { Route as AuthenticatedPostEditPostIdRouteImport } from './routes/_authenticated/post-edit.$postId'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagesRoute = AuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMConversationIdRoute =
  AuthenticatedMConversationIdRouteImport.update({
    id: '/m/$conversationId',
    path: '/m/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPPostIdRoute = AuthenticatedPPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPgSlugRoute = AuthenticatedPgSlugRouteImport.update({
  id: '/pg/$slug',
  path: '/pg/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostEditPostIdRoute =
  AuthenticatedPostEditPostIdRouteImport.update({
    id: '/post-edit/$postId',
    path: '/post-edit/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/m/$conversationId': typeof AuthenticatedMConversationIdRoute
  '/p/$postId': typeof AuthenticatedPPostIdRoute
  '/pg/$slug': typeof AuthenticatedPgSlugRoute
  '/post-edit/$postId': typeof AuthenticatedPostEditPostIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/m/$conversationId': typeof AuthenticatedMConversationIdRoute
  '/p/$postId': typeof AuthenticatedPPostIdRoute
  '/pg/$slug': typeof AuthenticatedPgSlugRoute
  '/post-edit/$postId': typeof AuthenticatedPostEditPostIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pages': typeof AuthenticatedPagesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/m/$conversationId': typeof AuthenticatedMConversationIdRoute
  '/_authenticated/p/$postId': typeof AuthenticatedPPostIdRoute
  '/_authenticated/pg/$slug': typeof AuthenticatedPgSlugRoute
  '/_authenticated/post-edit/$postId': typeof AuthenticatedPostEditPostIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/explore'
    | '/feed'
    | '/friends'
    | '/groups'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/pages'
    | '/settings'
    | '/m/$conversationId'
    | '/p/$postId'
    | '/pg/$slug'
    | '/post-edit/$postId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/explore'
    | '/feed'
    | '/friends'
    | '/groups'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/pages'
    | '/settings'
    | '/m/$conversationId'
    | '/p/$postId'
    | '/pg/$slug'
    | '/post-edit/$postId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/create'
    | '/_authenticated/explore'
    | '/_authenticated/feed'
    | '/_authenticated/friends'
    | '/_authenticated/groups'
    | '/_authenticated/me'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/pages'
    | '/_authenticated/settings'
    | '/_authenticated/m/$conversationId'
    | '/_authenticated/p/$postId'
    | '/_authenticated/pg/$slug'
    | '/_authenticated/post-edit/$postId'
    | '/_authenticated/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages': {
      id: '/_authenticated/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AuthenticatedPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/$conversationId': {
      id: '/_authenticated/m/$conversationId'
      path: '/m/$conversationId'
      fullPath: '/m/$conversationId'
      preLoaderRoute: typeof AuthenticatedMConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$postId': {
      id: '/_authenticated/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof AuthenticatedPPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pg/$slug': {
      id: '/_authenticated/pg/$slug'
      path: '/pg/$slug'
      fullPath: '/pg/$slug'
      preLoaderRoute: typeof AuthenticatedPgSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-edit/$postId': {
      id: '/_authenticated/post-edit/$postId'
      path: '/post-edit/$postId'
      fullPath: '/post-edit/$postId'
      preLoaderRoute: typeof AuthenticatedPostEditPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPagesRoute: typeof AuthenticatedPagesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMConversationIdRoute: typeof AuthenticatedMConversationIdRoute
  AuthenticatedPPostIdRoute: typeof AuthenticatedPPostIdRoute
  AuthenticatedPgSlugRoute: typeof AuthenticatedPgSlugRoute
  AuthenticatedPostEditPostIdRoute: typeof AuthenticatedPostEditPostIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPagesRoute: AuthenticatedPagesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMConversationIdRoute: AuthenticatedMConversationIdRoute,
  AuthenticatedPPostIdRoute: AuthenticatedPPostIdRoute,
  AuthenticatedPgSlugRoute: AuthenticatedPgSlugRoute,
  AuthenticatedPostEditPostIdRoute: AuthenticatedPostEditPostIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
